PX4-NuttX/nuttx branch test: px4-master_auto_rebase
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/px4-master_auto_rebase
 - https://github.com/PX4-NuttX/nuttx/commit/9a9032be622864132e97a6f8cfce7a372e10700b

Changes from PX4-NuttX/nuttx (https://github.com/PX4-NuttX/nuttx/commit/d5c12b24fa5349791220ce44a46b96f345ec77c1) in current PX4/master (e2eb84042e5d15b8212b0c0ccb9045c123c39284)
https://github.com/PX4-NuttX/nuttx/compare/d5c12b24fa5349791220ce44a46b96f345ec77c1...9a9032be622864132e97a6f8cfce7a372e10700b

9a9032b (HEAD, origin/px4-master_auto_rebase) [PX4: WIP] Fix transmission status handling in the serial interrupt
4c0232a [PX4: REJECTED] cstdint fix
00a8b53 [PX4: REJECTED] add math.h
b17bba4 [PX4: WIP] Jenkinsfile
9223123 (origin/master) arch/arm/src/stm32l4: Added custom pin mapping for STM32L4X2XX processors.
a3f80e1 binfmt/binfmt_execsymtab.c:  Fix a typo in a configuration variable name.
4d64862 arch/arm/src/stm32fy:  IO compensation is non longer an inline function, just a plain callable function.  Not really necessary for the F7, but now the implementation is identical to the F2 and F4.
871bfac arch/arm/src/stm32:  Use of inline function for I/O compensation causes too many issues.  No just a plain callable function.
c1a2c55 arch/arm/src/stm32/stm32_gpio.h:  Correct a recently introduced compilation error:  Not all STM32s have chip/stm32_syscfg.h
f09f186 arch/arm/src/stm32f7:  Port Bob Feritich's change (2c699d781279d899cffd0446d4073a9a6ea3fa48) to STM32 F2 and F4 which appear to have identical SD support and I/O compensation requirements.

Apps:
 - https://github.com/PX4-NuttX/apps/tree/px4-master_auto_rebase
 - https://github.com/PX4-NuttX/apps/commit/eb5c51575853b0e3746c0b624e12b0d67aeebd96

Changes from PX4-NuttX/apps (https://github.com/PX4-NuttX/apps/commit/36806ba3d84c0fa07ed86857d4c92a997b7cd194) in current PX4/master (e2eb84042e5d15b8212b0c0ccb9045c123c39284)
https://github.com/PX4-NuttX/apps/compare/36806ba3d84c0fa07ed86857d4c92a997b7cd194...eb5c51575853b0e3746c0b624e12b0d67aeebd96

eb5c515 (HEAD -> px4-master_auto_rebase, origin/px4-master_auto_rebase) [REJECTED] add-var-expansion-in-nsh-parse.patch
4db29bc (origin/master) apps/examples/elf:  Correct some Kconfig coments.
2ecc94f apps/import/Makefile:  Eliminate a MAKE sytax error that occurs in some (but not environments) when symtab.c has not been generated.
878fa8a Squashed commit of the following:
aea8d94 apps/examples/nsh:  The symbol table name and size variale names can now be configured.
5ecec24 There many occurences of the global variable g_exports and the opportunity for collisions.  Make the global variable names unique.
e778a69 Correct more improper global variable naming:  All must begin with g_
7c1082b apps/examples/nsh:  Clean up some rather complex conditional compilation associated with the previous commit.
0ea260e apps/examples/nsh:  Add logic to automatically register an application symbol table as part of NSH initialization.
6b93881 Merged in masayuki2009/nuttx.apps/fix_helloxx (pull request #144)